### ISSUE TITLE
feat(componentLoader): support different component loading strategies simultaneously

### ISSUE THREAD

**Issue by jvandemo** [angular/router#160] opened 2015-03-09 10:11 UTC
This is a proposal for making the component loader support different strategies at the same time.

### Current situation

Currently the component loader resolves the *component controller* and *component template* using the `$componentLoader` service.

We feed the *component name* into the service and get an object with the controller name and template to instantiate the component:

```javascript
{
  controllerName: 'SampleController',
  template: './components/sample/sample.html'
}
```

Using the `$componentLoaderProvider` we can overwrite the resolving functions to change the strategy globally to our liking.

### Drawback

The resolution strategy is global where individual components may use different strategies (ideally not, but realistically this will probably happen).

### Proposal

We could allow the controller name and template to be passed to the route config directly to "overwrite" the default behavior of the component loader:

```javascript
$router.config([
  {
    path: '/',
    component: {

        // We could use 'as' similar as in routes to
        // specify the name of the component because
        // we are dealing with an object now
        as: 'main',

        // Controller to instantiate as component controller
        controllerName: 'SomeDeviatingController',

        // What name to use to inject controller in template
        controllerAs: 'main',

        // Component template
        template: './components/other-location/template.html'
    }
  }
]);
```

### Implications

This would require the entire *instruction* to be passed into the `$componentLoader` service instead of just the *component name*.

It would also require more parsing of the arguments in the `$router.config()` method in case an object is received.

### Positive side effect

Passing the entire instruction to the component loader allows the loader functions to become more intelligent. Theoretically you could even pass meta data in the instruction (not sure if current implementation would allow this) to make routing decisions.

The default loader functions could then be an implementation of such *more intelligent* functions that first look whether the controller name and template are literally specified before attempting to apply the convention.

### Benefits

Possible benefits:

- being able to use different resolving strategies simultaneously
- you can *overwrite* the default behavior of the loader from within a single route config without having to change the component loader functions
- the loader functions themselves could be made more *intelligent* if they receive the entire instruction instead of just the component name

I think this could add a lot of power to the router, but would definitely need @btford's thoughts to see if it is technically doable.

**Comment by btford** [comment] 2015-03-09 17:18
Duplicate of #127, and something I definitely want to do. Let's continue discussion over there.

IMO, the path should be kept out of the route definition though.

**Closed by btford** 2015-03-09 17:18 UTC
