### ISSUE TITLE
Rationale behind the components directory

### ISSUE THREAD

**Issue by nareshbhatia** [angular/router#167] opened 2015-03-10 16:39 UTC
I notice that the new router assumes that components will be served from `./components` by default.

1. Is this a direction being taken by just the angular router or Angular 1.x/2.x in general?

2. While this behavior can be overridden by supplying a custom `$componentLoaderProvider`, I am wondering if this complication is necessary. We could quite easily avoid all this by specifying the location of the controller and the template in the router configuration (just like most other routers). For example:

```
    $router.config([
        {
            path: '/',
            templateUrl: 'dashboard/dashboard.html',
            controller: 'DashboardController',
        },
        {
            path: '/profile',
            templateUrl: 'profile/profile.html',
            controller: 'ProfileController'
        }
    ]);
```

While this configuration is a bit more verbose, it gives the flexibility to place our components anywhere we want.

I would appreciate some clarification on these questions.

**Comment by jeffwhelpley** [comment] 2015-03-10 22:17
@nareshbhatia I believe this was done to align the 1.x router with the 2.0 router. In 2.0, you are just dealing with components and the component will always define where the template is.

**Comment by btford** [comment] 2015-03-12 00:09
Duplicate of #127 – please check existing issues before posting new ones. Thanks!

**Closed by btford** 2015-03-12 00:09 UTC
