### ISSUE TITLE
Provide support for nesting under the components directory

### ISSUE THREAD

**Issue by ChrisPearce** [angular/router#146] opened 2015-03-02 17:27 UTC
For large projects, having a flat structure under the "components" directory quickly becomes unwieldily.

It would be useful to be able to implement a nested directory structure under the "components" directory by simple adding an extra property to the routes.
For example:
```javascript
  $router.config([
     { path: "/admin",  component: "myAdminComponent1", componentSubdirectory: "admin" },
     { path: "/admin",  component: "myAdminComponent2", componentSubdirectory: "admin" },
     { path: "/dashboard",  component: "myDashboardComponent1", componentSubdirectory: "dashboard" },
     { path: "/dashboard",  component: "myDashboardComponent2", componentSubdirectory: "dashboard" },
  ])
```

  This would then support a directory structure as follows:
```
    /components
       /admin
          /my-admin-component1
          /my-admin-component2
       /dashboard
          /my-dashboard-component1
          /my-dashboard-component2
```
          
An alternative would be to implement functionality similar to issue https://github.com/angular/router/issues/29 thereby allowing the $componentLoader to be configured to achieve the same result.

**Comment by sandelius** [comment] 2015-03-02 18:54
I like this a lot.

**Comment by maximilianmikus** [comment] 2015-03-07 19:40
+1

**Comment by krimple** [comment] 2015-03-11 20:05
+1 - I feel the structure of this components directory could get very wide very quickly - imagine several dozen routes and already you are going to start scanning directories with your eyes. I like sandelius's angle of using the pathing within component: personally.

**Comment by btford** [comment] 2015-03-12 00:11
This is definitely something I want to do.

This is a duplicate of #127 – let's all continue discussion there. Thanks!

**Closed by btford** 2015-03-12 00:11 UTC
