### ISSUE TITLE
defining components path via config variable

### ISSUE THREAD

**Issue by uztha4c** [angular/router#213] opened 2015-03-27 22:35 UTC
Is it possible to define the components folder location by passing it the path via a configuration variable? 

Right now it is set to look at "./components", but I think that should be the default, but can be overwritten if needed...as I needed to do since I am using it as part of a Salesforce VisualForce page implementation. I got it to work by just modify the code that has the path...but of course I will loose that whenever I update the router.es5.js file.

**Comment by btford** [comment] 2015-03-28 09:59
This is a duplicate of several other similar issues. Can you please check existing issues before posting a new on next time? This saves me lots of time. Thanks!

**Closed by btford** 2015-03-28 09:59 UTC
