### ISSUE TITLE
bug: component controllers instantiated twice

### ISSUE THREAD

**Issue by rohanrehman** [angular/router#236] opened 2015-04-03 22:29 UTC
Hi guys, I noticed all components in the examples are being instantiated twice.
Is this a default behaviour?

**Comment by skusunam** [comment] 2015-04-04 02:55
Duplicate of #204 ?

**Comment by rohanrehman** [comment] 2015-04-04 03:36
actually [#200](https://github.com/angular/router/issues/200)

**Comment by btford** [comment] 2015-04-04 09:04
Closing as a duplicate.

**Closed by btford** 2015-04-04 09:04 UTC
